//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiL.JS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiL.JS.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not assign to readonly property &quot;{0}&quot;.
        /// </summary>
        internal static string CannotAssignReadOnly {
            get {
                return ResourceManager.GetString("CannotAssignReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor cannot be static.
        /// </summary>
        internal static string ConstructorCannotBeStatic {
            get {
                return ResourceManager.GetString("ConstructorCannotBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not define a function inside a loop.
        /// </summary>
        internal static string FunctionInLoop {
            get {
                return ResourceManager.GetString("FunctionInLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &quot;{0}&quot; has already been declared.
        /// </summary>
        internal static string IdentifierAlreadyDeclared {
            get {
                return ResourceManager.GetString("IdentifierAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not increment property &quot;{0}&quot; without setter..
        /// </summary>
        internal static string IncrementPropertyWOSetter {
            get {
                return ResourceManager.GetString("IncrementPropertyWOSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not increment readonly &quot;{0}&quot;.
        /// </summary>
        internal static string IncrementReadonly {
            get {
                return ResourceManager.GetString("IncrementReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid left-hand side in assignment..
        /// </summary>
        internal static string InvalidLefthandSideInAssignment {
            get {
                return ResourceManager.GetString("InvalidLefthandSideInAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property name at {0}.
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process regular expression {0}.
        /// </summary>
        internal static string InvalidRegExp {
            get {
                return ResourceManager.GetString("InvalidRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; can not be called with new keyword.
        /// </summary>
        internal static string InvalidTryToCallWithNew {
            get {
                return ResourceManager.GetString("InvalidTryToCallWithNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; can not be called without new keyword.
        /// </summary>
        internal static string InvalidTryToCallWithoutNew {
            get {
                return ResourceManager.GetString("InvalidTryToCallWithoutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; can not be created with new keyword.
        /// </summary>
        internal static string InvalidTryToCreateWithNew {
            get {
                return ResourceManager.GetString("InvalidTryToCreateWithNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; can not be created without new keyword.
        /// </summary>
        internal static string InvalidTryToCreateWithoutNew {
            get {
                return ResourceManager.GetString("InvalidTryToCreateWithoutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments for function &quot;{0}&quot;.
        /// </summary>
        internal static string TooManyArgumentsForFunction {
            get {
                return ResourceManager.GetString("TooManyArgumentsForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get property &quot;{0}&quot; of &quot;{1}&quot;.
        /// </summary>
        internal static string TryingToGetProperty {
            get {
                return ResourceManager.GetString("TryingToGetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set property &quot;{0}&quot; of &quot;{1}&quot;.
        /// </summary>
        internal static string TryingToSetProperty {
            get {
                return ResourceManager.GetString("TryingToSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown identifier &quot;{0}&quot; at {1}.
        /// </summary>
        internal static string UnknowIdentifier {
            get {
                return ResourceManager.GetString("UnknowIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is not defined.
        /// </summary>
        internal static string VariableNotDefined {
            get {
                return ResourceManager.GetString("VariableNotDefined", resourceCulture);
            }
        }
    }
}
