[DATE].valueOf()

[DATE].getUTCDate()
[DATE].getUTCDay()
[DATE].getUTCFullYear()
[DATE].getUTCHours()
[DATE].getUTCMilliseconds()
[DATE].getUTCMinutes()
[DATE].getUTCMonth()
[DATE].getUTCSeconds()

[DATE].getDate()
[DATE].getDay()
[DATE].getYear()
[DATE].getFullYear()
[DATE].getHours()
[DATE].getMilliseconds()
[DATE].getMinutes()
[DATE].getMonth()
[DATE].getSeconds()

[DATE].toDateString()
[DATE].toISOString()
[DATE].toJSON()

[DATE].setMonth(5)
[DATE].setSeconds(55)
[DATE].setMilliseconds(555)
[DATE].setHours(4)
[DATE].setFullYear(2005)
[DATE].setDate(15)
[DATE].setMinutes(34)
[DATE].setDate(31)
[DATE].setTime(0)
[DATE].setTime(1525898414436)
    
[DATE].setUTCMonth(5)
[DATE].setUTCSeconds(55)
[DATE].setUTCMilliseconds(555)
[DATE].setUTCHours(4)
[DATE].setUTCFullYear(2004)
[DATE].setUTCDate(15)
[DATE].setUTCMinutes(34)

[DATE].toLocaleDateString()
[DATE].toLocaleTimeString()
[DATE].toString()
[DATE].toTimeString()
